version: '2'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/POSTGRES
      - SPRING_DATASOURCE_USERNAME=POSTGRES
      - SPRING_DATASOURCE_PASSWORD=POSTGRES
    networks:
      - host

  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_PASSWORD=POSTGRES
      - POSTGRES_USER=POSTGRES
      - POSTGRES_DB=POSTGRES
    networks:
      - host

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:4.29
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - host
networks:
  host:
    driver: bridge
volumes:
  db:

